#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    - name:  usermod -aG docker ubuntu
      shell: 
        cmd: "usermod -aG docker ubuntu" 


